export const myBlogs = [
  {
    img: "img/homeOfficeMain.jpg",
    alt: "picture of home office",
    date: "April 10, 2023",
    title: "My Journey to Software Development",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/jordan.jpg",
    alt: "picture of michael jordan on side of building",
    date: "March 28, 2023",
    title: "Chicago Bulls forever",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/hollywoodstudios.jpg",
    alt: "picture of toy story soldiers at hollywood studios",
    date: "Feb 28, 2023",
    title: "Hollywood Studios",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/mandolorian.jpg",
    alt: "picture of the mandolorian",
    date: "Jan 28, 2023",
    title: "Mandolorian, the best show?",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/soccer.jpg",
    alt: "picture of a live soccer event at a stadium",
    date: "Jan 28, 2023",
    title: "Real Madrid or Barcelona?",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/turntable.jpg",
    alt: "picture of dj cd turntables",
    date: "Dec 28, 2022",
    title: "The art of the Deejay",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
  {
    img: "img/xbox.jpg",
    alt: "picture of an xbox controller",
    date: "Nov 28, 2022",
    title: "Favorite game on xbox",
    text: "Cupcake ipsum dolor sit amet dragée carrot cake brownie. Gummies marzipan shortbread cotton candy tiramisu. Caramels bear claw toffee cake tart cake tootsie roll. Chocolate dragée tart pudding cupcake.",
  },
];
